### ISSUE TITLE
Serve index.js.txt

### ISSUE THREAD

**Issue by grifano** [oluwadareseyi/vite-webflow-starter#4]
Hi, thanks for the great template! I was thinking about using Vite for my setup, but your template fits my needs perfectly.

One thing that’s not working for me is serving index.js through Webflow assets, as mentioned in the README.

Should I replace ${hash} with my own URL from the assets panel? 
Thanks.

**Comment by oluwadareseyi** [comment]
Hello.

Yes, replace the entire URL with the URL to the asset.
